import type {
  Message,
  Order,
  Tailor,
  TailorAssignment,
  Collection,
} from '@/types/threadflow'

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    source: 'instagram',
    client_name: 'Adaeze Nwankwo',
    client_contact: '@adaeze.nw',
    content:
      'Good day! I love the Aso-oke gown you posted yesterday. Do you have it in coral and gold? I need it for a wedding on the 18th of July.',
    status: 'unresponded',
    category: 'enquiry',
    ai_draft: null,
    approved_at: null,
    created_at: '2026-06-25T08:12:00Z',
  },
  {
    id: 'msg-002',
    source: 'whatsapp',
    client_name: 'Chinedu Okafor',
    client_contact: '+234 803 555 1122',
    content:
      'Good afternoon ma, my fiancée and I want matching agbada and gown for our engagement next month. Can we book a fitting this week?',
    status: 'unresponded',
    category: 'enquiry',
    ai_draft:
      'Hi Chinedu, congratulations on the engagement! We would love to put together matching agbada and gown outfits for you both. We have fitting slots open this Thursday and Saturday — which works better?',
    approved_at: null,
    created_at: '2026-06-25T07:40:00Z',
  },
  {
    id: 'msg-003',
    source: 'website',
    client_name: 'Funmilayo Adebayo',
    client_contact: 'funmi.adebayo@gmail.com',
    content:
      'Submitted via contact form: Requesting a quote for a dinner gown in emerald lace, size 14, for a corporate dinner in the first week of July.',
    status: 'responded',
    category: 'enquiry',
    ai_draft:
      'Hi Funmilayo, thank you for reaching out! An emerald lace dinner gown in size 14 typically runs ₦65,000-₦95,000 depending on embellishment. We can have it ready before the first week of July if we start fittings this week. Would you like to schedule one?',
    approved_at: '2026-06-24T14:05:00Z',
    created_at: '2026-06-24T13:50:00Z',
  },
  {
    id: 'msg-004',
    source: 'instagram',
    client_name: 'Bisi Lawal',
    client_contact: '@bisilawal_',
    content:
      'Hello! Is the Ankara two-piece in your last post still available? I need it for a wedding guest look this weekend, can you rush it?',
    status: 'unresponded',
    category: 'enquiry',
    ai_draft: null,
    approved_at: null,
    created_at: '2026-06-25T09:02:00Z',
  },
  {
    id: 'msg-005',
    source: 'whatsapp',
    client_name: 'Ibrahim Suleiman',
    client_contact: '+234 805 222 9981',
    content:
      'Following up on my agbada order — has the cutting started? I paid the deposit two weeks ago.',
    status: 'unresponded',
    category: 'complaint',
    ai_draft: null,
    approved_at: null,
    created_at: '2026-06-25T06:55:00Z',
  },
  {
    id: 'msg-006',
    source: 'website',
    client_name: 'Patience Eze',
    client_contact: 'patience.eze@yahoo.com',
    content:
      'Order confirmation request: lace blouse and wrapper set agreed at ₦48,000, delivery on the 30th of June as discussed.',
    status: 'finalized',
    category: 'order_confirmation',
    ai_draft:
      'Confirmed, Patience! Your lace blouse and wrapper set is locked in at ₦48,000, delivery on June 30th. We will message you when it is ready for pickup.',
    approved_at: '2026-06-20T10:30:00Z',
    created_at: '2026-06-20T10:15:00Z',
  },
  {
    id: 'msg-007',
    source: 'instagram',
    client_name: 'Halima Bello',
    client_contact: '@halima.bello',
    content:
      'Hi! Do you use real Aso-oke or the cheaper blends? I want something authentic for my sister’s wedding.',
    status: 'responded',
    category: 'enquiry',
    ai_draft:
      'Hi Halima, we source authentic handwoven Aso-oke directly from Oyo weavers — no blends. Happy to send fabric swatches before you commit. When is the wedding?',
    approved_at: '2026-06-23T16:20:00Z',
    created_at: '2026-06-23T16:02:00Z',
  },
  {
    id: 'msg-008',
    source: 'whatsapp',
    client_name: 'Tobi Akinwale',
    client_contact: '+234 701 444 7765',
    content:
      "Can we negotiate the price for 3 dinner gowns? It's for my bridal train, we're on a budget.",
    status: 'unresponded',
    category: 'negotiation',
    ai_draft: null,
    approved_at: null,
    created_at: '2026-06-25T05:48:00Z',
  },
  {
    id: 'msg-009',
    source: 'website',
    client_name: 'Grace Umeh',
    client_contact: 'grace.umeh@outlook.com',
    content:
      "I need an agbada for my dad's 60th birthday — can you do gold embroidery on navy guinea fabric within 2 weeks?",
    status: 'unresponded',
    category: 'enquiry',
    ai_draft:
      'Hi Grace, a navy guinea agbada with gold embroidery is very doable within 2 weeks. We will need your father’s measurements to get started — do you have them on hand?',
    approved_at: null,
    created_at: '2026-06-24T19:30:00Z',
  },
  {
    id: 'msg-010',
    source: 'instagram',
    client_name: 'Zainab Mohammed',
    client_contact: '@zainabm_',
    content:
      'Thank you so much, the lace gown fits perfectly! Sending payment for the balance now.',
    status: 'finalized',
    category: 'order_confirmation',
    ai_draft: null,
    approved_at: '2026-06-22T11:10:00Z',
    created_at: '2026-06-22T11:00:00Z',
  },
  {
    id: 'msg-011',
    source: 'whatsapp',
    client_name: 'Olumide Fashola',
    client_contact: '+234 802 991 3340',
    content:
      "I'm not happy — the shirt I picked up yesterday has loose buttons already. Can someone fix this?",
    status: 'unresponded',
    category: 'complaint',
    ai_draft: null,
    approved_at: null,
    created_at: '2026-06-25T07:05:00Z',
  },
  {
    id: 'msg-012',
    source: 'website',
    client_name: 'Ngozi Iweka',
    client_contact: 'ngozi.iweka@gmail.com',
    content:
      'Quote request: Ankara Kaftan for a baby naming ceremony, size 16, need it in 10 days.',
    status: 'responded',
    category: 'enquiry',
    ai_draft:
      'Hi Ngozi, an Ankara kaftan in size 16 within 10 days is achievable. Pricing depends on fabric choice — would you like to come in to pick a print, or should we suggest a few?',
    approved_at: '2026-06-24T09:15:00Z',
    created_at: '2026-06-24T08:58:00Z',
  },
  {
    id: 'msg-013',
    source: 'instagram',
    client_name: 'Folake Adeyemi',
    client_contact: '@folakeadeyemi',
    content:
      "Can you do a custom wedding guest dinner gown in dusty rose lace? I'm thinking knee length with long sleeves.",
    status: 'unresponded',
    category: 'enquiry',
    ai_draft:
      'Hi Folake, a dusty rose lace dinner gown, knee length with long sleeves, sounds beautiful and is very achievable. Do you have an event date in mind so we can confirm timeline?',
    approved_at: null,
    created_at: '2026-06-25T10:20:00Z',
  },
  {
    id: 'msg-014',
    source: 'whatsapp',
    client_name: 'Yusuf Garba',
    client_contact: '+234 706 888 2210',
    content:
      'We agreed on ₦120,000 for the agbada set with cap, delivery before the 10th of July. Just confirming once more before I send the deposit.',
    status: 'responded',
    category: 'negotiation',
    ai_draft:
      'Confirmed, Yusuf — ₦120,000 for the full agbada set with cap, delivery before July 10th. Send the deposit whenever you are ready and we will get the cutting scheduled.',
    approved_at: '2026-06-24T17:45:00Z',
    created_at: '2026-06-24T17:30:00Z',
  },
  {
    id: 'msg-015',
    source: 'website',
    client_name: 'Comfort Nnamdi',
    client_contact: 'comfort.nnamdi@gmail.com',
    content:
      'Booking confirmed for 2 Ankara dinner gowns, deposit paid, balance on pickup the 16th of July.',
    status: 'finalized',
    category: 'order_confirmation',
    ai_draft:
      'All set, Comfort! Both Ankara dinner gowns are booked, deposit received, balance due on pickup July 16th.',
    approved_at: '2026-06-19T12:40:00Z',
    created_at: '2026-06-19T12:25:00Z',
  },
]

export const mockTailors: Tailor[] = [
  {
    id: 't-1',
    name: 'Ngozi Chukwu',
    specialty: 'Bridal & Aso-Oke',
    current_load: 14,
    is_available: true,
  },
  {
    id: 't-2',
    name: 'Emeka Obi',
    specialty: 'Agbada & Menswear',
    current_load: 6,
    is_available: true,
  },
  {
    id: 't-3',
    name: 'Amara Eze',
    specialty: 'Ankara & Everyday Wear',
    current_load: 18,
    is_available: false,
  },
  {
    id: 't-4',
    name: 'Tunde Bakare',
    specialty: 'Lace & Evening Gowns',
    current_load: 9,
    is_available: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ord-001',
    message_id: 'msg-010',
    client_name: 'Zainab Mohammed',
    cloth_type: 'Lace Gown',
    description: 'Fitted lace evening gown, champagne, size 10, final fitting done',
    deadline: '2026-06-28',
    order_type: 'bespoke',
    collection_id: null,
    status: 'ready',
    tailor_confirmed: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'ord-002',
    message_id: 'msg-006',
    client_name: 'Patience Eze',
    cloth_type: 'Lace Blouse & Wrapper Set',
    description: 'Royal blue lace blouse and wrapper, gold trim, size 14',
    deadline: '2026-06-30',
    order_type: 'bespoke',
    collection_id: null,
    status: 'in_production',
    tailor_confirmed: true,
    created_at: '2026-06-20T10:30:00Z',
  },
  {
    id: 'ord-003',
    message_id: null,
    client_name: 'Kelechi Nwosu',
    cloth_type: 'Ankara Two-Piece (Collection)',
    description: 'Ready-to-wear Ankara two-piece from the Owambe Ready-to-Wear collection, size M',
    deadline: '2026-07-02',
    order_type: 'collection',
    collection_id: 'col-001',
    status: 'delivered',
    tailor_confirmed: true,
    created_at: '2026-06-17T13:00:00Z',
  },
  {
    id: 'ord-004',
    message_id: 'msg-003',
    client_name: 'Funmilayo Adebayo',
    cloth_type: 'Lace Dinner Gown',
    description: 'Emerald lace dinner gown for a corporate dinner, size 14',
    deadline: '2026-07-04',
    order_type: 'bespoke',
    collection_id: null,
    status: 'confirmed',
    tailor_confirmed: false,
    created_at: '2026-06-24T14:10:00Z',
  },
  {
    id: 'ord-005',
    message_id: 'msg-007',
    client_name: 'Halima Bello',
    cloth_type: 'Aso-Oke Wedding Set',
    description: 'Authentic handwoven Aso-oke iro and buba, coral and gold weave',
    deadline: '2026-07-07',
    order_type: 'bespoke',
    collection_id: null,
    status: 'in_production',
    tailor_confirmed: true,
    created_at: '2026-06-23T16:30:00Z',
  },
  {
    id: 'ord-006',
    message_id: 'msg-014',
    client_name: 'Yusuf Garba',
    cloth_type: 'Agbada Set',
    description: 'Agbada with matching cap, navy guinea brocade, gold embroidery',
    deadline: '2026-07-10',
    order_type: 'bespoke',
    collection_id: null,
    status: 'confirmed',
    tailor_confirmed: true,
    created_at: '2026-06-24T17:50:00Z',
  },
  {
    id: 'ord-007',
    message_id: null,
    client_name: 'Aisha Bello',
    cloth_type: 'Agbada (Collection)',
    description: 'Ready-to-wear agbada from the Agbada Capsule collection, size L',
    deadline: '2026-07-13',
    order_type: 'collection',
    collection_id: 'col-002',
    status: 'ready',
    tailor_confirmed: true,
    created_at: '2026-06-21T08:20:00Z',
  },
  {
    id: 'ord-008',
    message_id: 'msg-015',
    client_name: 'Comfort Nnamdi',
    cloth_type: 'Ankara Dinner Gown',
    description: 'Two Ankara dinner gowns, navy and burgundy prints, sizes 12 and 16',
    deadline: '2026-07-16',
    order_type: 'bespoke',
    collection_id: null,
    status: 'confirmed',
    tailor_confirmed: true,
    created_at: '2026-06-19T12:45:00Z',
  },
]

export const mockTailorAssignments: TailorAssignment[] = [
  {
    id: 'asn-001',
    order_id: 'ord-001',
    tailor_id: 't-4',
    role_description: 'Final fitting adjustments and pressing',
    approved_by_tailor: true,
    edited_by_tailor: false,
    assigned_at: '2026-06-18T10:00:00Z',
  },
  {
    id: 'asn-002',
    order_id: 'ord-002',
    tailor_id: 't-1',
    role_description: 'Lead seamstress — blouse construction and gold trim finishing',
    approved_by_tailor: true,
    edited_by_tailor: false,
    assigned_at: '2026-06-21T09:30:00Z',
  },
  {
    id: 'asn-003',
    order_id: 'ord-005',
    tailor_id: 't-1',
    role_description: 'Aso-oke weaving liaison and iro/buba assembly',
    approved_by_tailor: true,
    edited_by_tailor: true,
    assigned_at: '2026-06-23T18:00:00Z',
  },
  {
    id: 'asn-004',
    order_id: 'ord-004',
    tailor_id: 't-4',
    role_description: 'Lace gown pattern draft and beadwork',
    approved_by_tailor: false,
    edited_by_tailor: false,
    assigned_at: '2026-06-24T15:00:00Z',
  },
  {
    id: 'asn-005',
    order_id: 'ord-006',
    tailor_id: 't-2',
    role_description: 'Agbada cutting and gold embroidery oversight',
    approved_by_tailor: false,
    edited_by_tailor: false,
    assigned_at: '2026-06-24T18:10:00Z',
  },
]

export const mockCollections: Collection[] = [
  {
    id: 'col-001',
    name: 'Owambe Ready-to-Wear',
    description:
      'Pre-made aso-ebi sets in classic lace and Ankara prints, ready for same-week pickup.',
    pieces_available: 12,
    created_at: '2026-05-30T09:00:00Z',
  },
  {
    id: 'col-002',
    name: 'Agbada Capsule',
    description: 'Limited run of premium agbada sets in guinea brocade, sizes M-XXL.',
    pieces_available: 6,
    created_at: '2026-06-10T09:00:00Z',
  },
]
