'use client'

import { useEffect, useRef, useState } from 'react'
import { BriefCard } from './BriefCard'
import type { BriefSnapshot } from '@/lib/brief'

type Status = 'idle' | 'loading' | 'streaming' | 'done' | 'error'

export function BriefClient({ snapshot }: { snapshot: BriefSnapshot }) {
  const [briefText, setBriefText] = useState('')
  const [status, setStatus] = useState<Status>('idle')
  const abortRef = useRef<AbortController | null>(null)

  async function generate() {
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller

    setStatus('loading')
    setBriefText('')

    try {
      const res = await fetch('/api/brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(snapshot),
        signal: controller.signal,
      })

      if (!res.ok || !res.body) {
        throw new Error('Failed to generate brief')
      }

      setStatus('streaming')
      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let fullText = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        fullText += decoder.decode(value, { stream: true })
        setBriefText(fullText)
      }

      // The stream can end with zero bytes after a 200 response (e.g. an
      // upstream provider error) — treat an empty result as a failure.
      setStatus(fullText.trim() ? 'done' : 'error')
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') return
      setStatus('error')
    }
  }

  useEffect(() => {
    void Promise.resolve().then(generate)
    return () => abortRef.current?.abort()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <main className="px-10 py-10 pb-16">
      <header className="mb-10">
        <span className="text-label-caps font-label-caps text-on-surface-variant uppercase tracking-widest">
          AI Operations Assistant
        </span>
        <h1 className="font-headline-lg text-headline-lg text-primary mt-1">Brief Me</h1>
        <p className="text-body-lg font-body-lg text-on-surface-variant max-w-xl mt-2">
          A fresh, data-grounded summary of your studio — generated by Gemini.
        </p>
      </header>

      <BriefCard snapshot={snapshot} briefText={briefText} status={status} onRegenerate={generate} />
    </main>
  )
}
